# Description: This file contains the deployment and service configuration for the application.  ha20003660/azure-fusion:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-fusion
  namespace: default
  labels:
    app: azure-fusion
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: azure-fusion
  template:
    metadata:
      labels:
        app: azure-fusion
    spec:
      containers:
        - name: azure-fusion
          image: azurefusion.azurecr.io/azure-fusion:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
          ports:
            - name: http-port
              containerPort: 8080
          env:
            - name: client.azureopenai.key
              value: ${AZURE_OPENAI_KEY:demo}
            - name: client.azureopenai.endpoint
              value: ${AZURE_OPENAI_ENDPOINT:https://uba-pj-etmpayments-openai.openai.azure.com/}
            - name: client.azureopenai.deploymentname
              value: ${AZURE_OPENAI_DEPLOYMENT_NAME:gpt-4o}
            - name: client.azureopenai.embedding.model
              value: ${EMBEDDING_MODEL_NAME:text-embedding-3-small}
            - name: client.azureopenai.embedding.dimension
              value: ${EMBEDDING_MODEL_DIMENSION:1536}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http-port
            initialDelaySeconds: 60
            periodSeconds: 120
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: azure-fusion
  namespace: default
  labels:
    app: azure-fusion
spec:
  type: LoadBalancer
  selector:
    app: azure-fusion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000

